eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    
microservice:
  product-service:
    endpoints:
      endpoint:
        uri: "http://product-service/api/product/get/"
  category-service:
    endpoints:
      endpoint:
        uri: "http://product-service/api/category/get/"
  user-service:
    endpoints:
      endpoint:
        uri: "http://user-service/api/user/get/"
  discount-service:
    endpoints:
      endpoint:
        uri: "http://discount-service/api/coupon/"
